name: shell commands
on: 
  - push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v1 #This will copy our code into the runner
    - name: Set Terraform 
      uses: hashicorp/setup-terraform@v2 #This will install terraform into the runner
      with: 
        terraform_version: 1.1.9 #With what version of terraform
    - name: Running Terraform command (Terraform init)
      run: terraform init
    - name: Multi line string
      run: |
        pwd
        node -v
        ls -a


