name: shell commands
on: 
  - push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
    - name: echo string
      run: echo "Hello"
    - name: Multi line string
      run: |
        pwd
        node -v
        ls -a
    - name: python command
      run: |
        import platform
        print(platform.processor())
      shell: python
#Running multiple jobs with different os
  run-windows-commands:
    runs-on: windows-latest
#To make this job run in series i.e (run one job first b4 the other use the needs instruction)
    needs: ["run-shell-commands"]
    steps:
    - name: print working Directory
      run: pwd
      shell: bash


